services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: "1000:1000"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:11.6.1
    container_name: grafana
    restart: always
    user: "1000:1000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Toxicdown102105!
      - GF_SECURITY_COOKIE_SAMESITE=disabled
      - GF_SECURITY_COOKIE_SECURE=false
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    user: "1000:1000"
    volumes:
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/rootfs'
    ports:
      - "9100:9100"
    networks:
      - monitoring_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    user: "0:0"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - monitoring_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    user: "10001:10001"
    volumes:
      - ./loki/config:/etc/loki
      - ./loki/data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    networks:
      - monitoring_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    user: "1000:1000"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"
    networks:
      - monitoring_net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ./promtail/config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    ports:
      - "9080:9080"
    networks:
      - monitoring_net

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    user: "1000:1000"
    environment:
      POSTGRES_PASSWORD: Toxicdown102105!
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitoring_net

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: always
    ports:
      - "9115:9115"
    networks:
      - monitoring_net

networks:
  monitoring_net:
    external: true
